### ISSUE TITLE
Failing Test in Node 7.10: Contextual promise should contextify errors raised in then handler

### ISSUE THREAD

**Issue by FokkeZB** [zapier/zapier-platform-core#36]
```
  1 failing

  1) contextual promise should contextify errors raised in then handler:
     AssertionError: expected 'Error: whoops contextified!' to match /^Error: whoops$/
      at Assertion.fail (node_modules/should/cjs/should.js:205:17)
      at Assertion.value [as match] (node_modules/should/cjs/should.js:277:19)
      at Object.promise.then.catch.err (test/tools/promise.js:45:31)
  From previous event:
      at Context.it (test/tools/promise.js:40:13)
```

**Comment by FokkeZB** [comment]
There are also 3 pending:

```
    1) should contextify errors raised in then handler
    - should contextify errors thrown by promises returned from then handler
    - should contextify errors rejected by promises returned from then handler
    - should handle rejected outright promises
```

**Comment by FokkeZB** [comment]
Test passed with Node 4.3.2, although the 3 pending are still there. Perhaps we should check Node version matches the one in `.nvmrc` before running the tests?

**Comment by xavdid** [comment]
@FokkeZB the pending tests are tests that haven't been written, so those are safe to ignore. 

We now check node version as part of `zapier test`. Are these an issue on `6.10.2`?

**Comment by FokkeZB** [comment]
Now that we check the node version as part of `zapier test` we can close this.
